title: Rye Scholin Portfolio
description: > # this means to ignore newlines until "baseurl:"
  Rye Scholin Project Portfolio
permalink: ":title/"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Rye Scholin
author-img: rye-scholin.png
about-author: |
  I am a computer science and computer engineering student focused on app development, software architecture, 
  embedded systems, and networking. 

  With a strong foundation in programming and systems design, I’m passionate about building efficient, 
  scalable, and innovative solutions.
social-twitter:
social-facebook:
social-github: ryescholin
social-linkedin: rye-scholin-b8605a18a
social-email: ryescholin@gmail.com

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
